<?php include 'header.phtml'; ?>

<h2>Add Vocabularies</h2>

<form action="<?php echo $set->get_add_link(); ?>" method="post">

<ol id="addlist">
    <?php for ($i = 0; $i < 2; $i++): ?>
    <li>
        <p>
            <label>
                Front:
                <input type="text" name="front[]"<?php if ($i == 0): ?> autofocus<?php endif; ?> />
            </label>
        </p>
        <p>
            <label>
                Back:
                <textarea name="back[]"></textarea>
            </label>
        </p>
        <p>
            <label>
                Notes:
                <textarea name="notes[]"></textarea>
            </label>
        </p>
    </li>
    <?php endfor; ?>
</ol>

<p>
    <button type="submit">Submit</button>
</p>

</form>

<?php include 'footer.phtml'; ?>
