<?php include 'header.phtml'; ?>

<h2>Dashboard</h2>

<h3>Statistics</h3>

<ul>
    <li>
        Next review:
        <?php
            if (!$next_review_vocab) echo 'None';
            else echo $next_review_vocab->get_human_due_date();
        ?>
    </li>
    <li>
        Due tomorrow:
        <?php echo Vocabulary::filter('in_set', $set)->filter('due_tomorrow')->count(); ?>
    </li>
</ul>

<h3>Levels</h3>

<ol>
    <li>
        Inactive:
        <?php echo Vocabulary::filter('in_set', $set)->filter('inactive')->count(); ?>
    </li>
    <li>
        Apprentice:
        <?php echo Vocabulary::filter('in_set', $set)->filter('level', 0, 2)->count(); ?>
    </li>
    <li>
        Guru:
        <?php echo Vocabulary::filter('in_set', $set)->filter('level', 3, 4)->count(); ?>
    </li>
    <li>
        Master:
        <?php echo Vocabulary::filter('in_set', $set)->filter('level', 5, 5)->count(); ?>
    </li>
    <li>
        Enlightened:
        <?php echo Vocabulary::filter('in_set', $set)->filter('level', 6, 6)->count(); ?>
    </li>
    <li>
        Burned:
        <?php echo Vocabulary::filter('in_set', $set)->filter('level', 7, 7)->count(); ?>
    </li>
</ol>

<h3>Sets</h3>

<ul>
    <?php foreach ($sets as $set): ?>
        <li<?php if ($set->id == $set->id): ?> class="active"<?php endif; ?>>
            <a href="<?php echo $set->get_permalink(); ?>"><?php echo $set->name; ?></a>
            <?php echo $set->get_new_vocabularies()->count() + $set->get_due_vocabularies()->count(); ?>
        </li>
    <?php endforeach; ?>
    <li>
        <a href="#">Create Set</a>
    </li>
</ul>

<?php include 'footer.phtml'; ?>
