<?php include 'header.phtml'; ?>

<h2>Dashboard</h2>

<h3>Statistics</h3>

<ul class="stats">
    <li>
        Next review in
        <?php if (!$next_review_vocab): ?>
            <span>None</span>
        <?php else: ?>
            <time
                datetime="<?php p($next_review_vocab->get_due_date()->format('Y-m-d H:i:s')); ?>"
                title="<?php p($next_review_vocab->get_due_date()->format('r')); ?>"
            >~<?php p($next_review_vocab->get_human_due_date()); ?></time>
        <?php endif; ?>
    </li>
    <li>
        Due next hour
        <?php if(!isset($set)): ?>
            <span>None</span>
        <?php else: ?>
            <span><?php p(Vocabulary::filter('in_set', $set)->filter('due_next_hour')->count()); ?></span>
        <?php endif; ?>

    </li>
    <li>
        Due tomorrow
        <?php if(!isset($set)): ?>
            <span>None</span>
        <?php else: ?>
            <span><?php p(Vocabulary::filter('in_set', $set)->filter('due_tomorrow')->count()); ?></span>
         <?php endif; ?>   
    </li>
</ul>

<ol class="stats levels">
    <li>
        Inactive
        <?php if(!isset($set)): ?>
            <span>0</span>
        <?php else: ?>
        <span><?php p(Vocabulary::filter('in_set', $set)->filter('inactive')->count()); ?></span>
        <?php endif; ?> 
    </li>
    <li>
        Apprentice
        <?php if(!isset($set)): ?>
            <span>0</span>
        <?php else: ?>
            <span><?php p(Vocabulary::filter('in_set', $set)->filter('level', 0, 3)->count()); ?></span>
        <?php endif; ?> 
    </li>
    <li>
        Guru
        <?php if(!isset($set)): ?>
            <span>0</span>
        <?php else: ?>            
            <span><?php p(Vocabulary::filter('in_set', $set)->filter('level', 4, 5)->count()); ?></span>
        <?php endif; ?> 
    </li>
    <li>
        Master
        <?php if(!isset($set)): ?>
            <span>0</span>
        <?php else: ?>            
            <span><?php p(Vocabulary::filter('in_set', $set)->filter('level', 6, 6)->count()); ?></span>
        <?php endif; ?> 
    </li>
    <li>
        Enlightened
        <?php if(!isset($set)): ?>
            <span>0</span>
        <?php else: ?>            
            <span><?php p(Vocabulary::filter('in_set', $set)->filter('level', 7, 7)->count()); ?></span>
        <?php endif; ?> 
    </li>
    <li>
        Burned
        <?php if(!isset($set)): ?>
            <span>0</span>
        <?php else: ?>            
            <span><?php p(Vocabulary::filter('in_set', $set)->filter('level', 8, 8)->count()); ?></span>
        <?php endif; ?> 
    </li>
</ol>

<h3 class="hastasks">Sets</h3>

<ul class="tasks">
    <li>
        <a href="<?php p(BASE_PATH); ?>create">Create Set</a>
    </li>
</ul>

<ul class="sets">
    <?php foreach ($sets as $set): ?>
        <li<?php if ($set->id == $set->id): ?> class="active"<?php endif; ?>>
            <a href="<?php p($set->get_permalink()); ?>"><?php p($set->name); ?></a>

            <?php

            $count = count($set->get_new_vocabularies()->find_many()) + count($set->get_due_vocabularies()->find_many());

            ?>
            <?php if ($count != 0): ?>
            <span>
            <?php p($count); ?>
            </span>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>

<?php include 'footer.phtml'; ?>
