<?php include 'header.phtml'; ?>

<h2><?php echo $title; ?></h2>

<form action="<?php echo $action; ?>" method="post">
    <p>
        <label>
            Name:
            <input type="text" name="name" value="<?php if ($set) echo htmlentities($set->name); ?>" autofocus />
        </label>
    </p>
    <p>
        <button type="submit">Update</button>
    </p>
</form>

<?php include 'footer.phtml'; ?>
