<?php include 'header.phtml'; ?>

<h2><?php p($title); ?></h2>

<form action="<?php p($action); ?>" method="post">
    <p>
        <label>
            Name:
            <input type="text" name="name" value="<?php isset($set) ? p($set->name) : ''; ?>" autofocus placeholder="Enter Set Name"/>
        </label>
    </p>
    <p>
        <label>
            New Items Per Day:
            <input
                type="number"
                name="new_per_day"
                min="0"
                value="<?php isset($set) ? p($set->new_per_day) : p('10'); ?>"
            />
        </label>
    </p>
    <p>
        <button type="submit">Update</button>
    </p>
</form>

<?php include 'footer.phtml'; ?>
