<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<title><?php echo $title; ?> &mdash; Recall</title>

<meta name="viewport" content="width=device-width, user-scalable=no">
<link rel="stylesheet" type="text/css" href="<?php echo BASE_PATH; ?>css/recall.css" />
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>

</head>
<body>

<header>
    <h1><a href="<?php echo BASE_PATH; ?>">Recall</a></h1>
</header>

<main>
