<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<title><?php p($title); ?> &mdash; Recall</title>

<meta name="viewport" content="width=device-width, user-scalable=no">
<link rel="stylesheet" type="text/css" href="<?php p(BASE_PATH); ?>css/recall.css" />
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="<?php p(BASE_PATH); ?>js/autosize.min.js"></script>
<script src="<?php p(BASE_PATH); ?>js/global.js"></script>

</head>
<body>

<div id="wrapper">
<header>
    <?php if (isset($backlink)): ?>
    <a class="back" href="<?php p($backlink); ?>">&larr; <?php p($backtext); ?></a>
    <?php endif; ?>
    <h1><a href="<?php p(BASE_PATH); ?>">Recall</a></h1>
</header>

<main>
