<?php include 'header.phtml'; ?>

<h2>Score &mdash; <?php echo round(count($correct) * 100 / (count($incorrect) + count($correct))); ?>%</h2>

<?php if (count($incorrect) != 0): ?>

<h3>Level Down</h3>

<ul class="vocabularies">
    <?php foreach ($incorrect as $vocab): ?>
    <li class="<?php echo strtolower($vocab->get_human_level()); ?>">
        <a href="<?php echo $vocab->get_permalink(); ?>">
            <?php echo htmlentities($vocab->front); ?>
        </a>
    </li>
    <?php endforeach; ?>
</ul>

<?php endif; ?>

<?php if (count($correct) != 0): ?>

<h3>Level Up</h3>

<ul class="vocabularies">
    <?php foreach ($correct as $vocab): ?>
    <li class="<?php echo strtolower($vocab->get_human_level()); ?>">
        <a href="<?php echo $vocab->get_permalink(); ?>">
            <?php echo htmlentities($vocab->front); ?>
        </a>
    </li>
    <?php endforeach; ?>
</ul>

<?php endif; ?>

<?php include 'footer.phtml'; ?>
