<?php include 'header.phtml'; ?>

<h2>Score</h2>

<ol class="progress">
    <li class="correct" title="Correct">Correct: <span><?php p(count($correct)); ?></span></li>
    <li title="Incorrect">Incorrect: <span><?php p(count($incorrect)); ?></span></li>
</ol>

<?php if (count($incorrect) != 0): ?>

<h3>Level Down</h3>

<ul class="vocabularies">
    <?php foreach ($incorrect as $vocab): ?>
    <li class="<?php p(strtolower($vocab->get_human_level())); ?>">
        <a href="<?php p($vocab->get_permalink()); ?>">
            <?php p($vocab->front); ?>
        </a>
    </li>
    <?php endforeach; ?>
</ul>

<?php endif; ?>

<?php if (count($correct) != 0): ?>

<h3>Level Up</h3>

<ul class="vocabularies">
    <?php foreach ($correct as $vocab): ?>
    <li class="<?php p(strtolower($vocab->get_human_level())); ?>">
        <a href="<?php p($vocab->get_permalink()); ?>">
            <?php p($vocab->front); ?>
        </a>
    </li>
    <?php endforeach; ?>
</ul>

<?php endif; ?>

<?php include 'footer.phtml'; ?>
