<?php include 'header.phtml'; ?>

<h2>Set: <?php echo $set->name; ?></h2>

<ul class="tasks">
    <?php if (count($new_vocabs) != 0): ?>
        <li><a href="<?php echo $set->get_learn_link(); ?>">Learn</a> <?php echo count($new_vocabs); ?></li>
    <?php endif; ?>
    <?php if (count($due_vocabs) != 0): ?>
        <li><a href="<?php echo $set->get_review_link(); ?>">Review</a> <?php echo count($due_vocabs); ?></li>
    <?php endif; ?>
    <li><a href="<?php echo $set->get_add_link(); ?>">Add Vocabulary</a></li>
</ul>

<?php if (count($vocabularies) != 0): ?>

<ol class="vocabularies">
    <?php foreach ($vocabularies as $vocab): ?>
        <li<?php
            if (!$vocab->is_active()): ?> class="inactive"<?php
            elseif ($vocab->is_burned()): ?> class="burned"<?php
            endif; ?>>
            <a href="<?php echo $vocab->get_permalink(); ?>"><?php echo $vocab->front; ?></a>
        </li>
    <?php endforeach; ?>
</ol>

<?php endif; ?>

<?php include 'footer.phtml'; ?>
