<?php include 'header.phtml'; ?>

<h2>Set: <?php echo $set->name; ?></h2>

<form action="<?php echo $set->get_delete_link(); ?>" method="post">

<ul class="tasks">
    <?php if (count($new_vocabs) != 0): ?>
    <li>
        <a href="<?php echo $set->get_learn_link(); ?>">Learn</a>
        <span><?php echo count($new_vocabs); ?></span>
    </li>
    <?php endif; ?>
    <?php if (count($due_vocabs) != 0): ?>
    <li>
        <a href="<?php echo $set->get_review_link(); ?>">Review</a>
        <span><?php echo count($due_vocabs); ?></span>
    </li>
    <?php endif; ?>
    <li><a href="<?php echo $set->get_add_link(); ?>">Add</a></li>
    <li><a href="<?php echo $set->get_edit_link(); ?>">Edit</a></li>
    <li><button type="submit" class="delete">Delete</button></li>
</ul>

</form>

<h3>Progress</h3>

<ol class="progress">
    <li class="burned" title="Burned">
        Burned:
        <span><?php echo $stats['burned']; ?></span>
    </li>
    <li class="active" title="Active">
        Active:
        <span><?php echo $stats['active']; ?></span>
    </li>
    <li title="Inactive">
        Inactive:
        <span><?php echo $stats['inactive']; ?></span>
    </li>
</ol>

<?php if (count($critical_vocabs) != 0): ?>

<h3>Critical Items</h3>

<ol class="vocabularies">
    <?php foreach ($critical_vocabs as $vocab): ?>
        <li class="<?php echo strtolower($vocab->get_human_level()); ?>">
            <a href="<?php echo $vocab->get_permalink(); ?>"><?php echo htmlentities($vocab->front); ?></a>
        </li>
    <?php endforeach; ?>
</ol>

<?php endif; ?>

<?php if (count($vocabularies) != 0): ?>

<h3>Vocabulary</h3>

<ol class="vocabularies">
    <?php foreach ($vocabularies as $vocab): ?>
        <li class="<?php echo strtolower($vocab->get_human_level()); ?>">
            <a href="<?php echo $vocab->get_permalink(); ?>"><?php echo htmlentities($vocab->front); ?></a>
        </li>
    <?php endforeach; ?>
    <?php if ($has_nextpage): ?>
        <li class="more">
            <a href="<?php echo $nextpage_link; ?>" title="Load More">&hellip;</a>
        </li>
    <?php endif; ?>
</ol>

<?php endif; ?>

<?php include 'footer.phtml'; ?>
