<?php include 'header.phtml'; ?>

<h2><?php echo $title; ?></h2>

<?php if (count($vocabularies) == 0): ?>

<p>There&rsquo;s nothing to study.</p>

<?php else: ?>

<form action="<?php echo $action; ?>" method="post">
    <ol id="study">
        <?php foreach ($vocabularies as $vocab): ?>

        <li>
            <?php if ($vocab->is_active()): ?>
                <p class="meta">
                    Level <?php echo $vocab->get_human_level(); ?>
                </p>
            <?php endif; ?>

            <h3><?php echo htmlentities($vocab->front); ?></h3>

            <section class="back">
                <p class="tasks"><a href="<?php echo $vocab->get_permalink(); ?>">Edit</a></p>

                <div class="inner">
                    <?php echo $vocab->get_back(); ?>
                </div>
            </section>

            <textarea name="back-<?php echo $vocab->id; ?>" placeholder="Back"><?php
                echo htmlentities($vocab->back);
            ?></textarea>

            <section class="notes">
                <div class="inner">
                    <?php echo $vocab->get_notes(); ?>
                </div>
            </section>

            <textarea name="notes-<?php echo $vocab->id; ?>" placeholder="Notes"><?php
                echo htmlentities($vocab->notes);
            ?></textarea>

            <p>
                <label>
                    <input type="checkbox" name="correct-<?php echo $vocab->id; ?>" />
                    Correct
                </label>
            </p>
        </li>

        <?php endforeach; ?>
    </ol>

    <p>
        <input type="hidden" name="ids" value="<?php echo $ids; ?>">
        <input type="hidden" name="mode" value="<?php echo $mode; ?>">
        <button type="submit">Submit</button>
    </p>
</form>

<?php endif; ?>

<?php include 'footer.phtml'; ?>
