<?php include 'header.phtml'; ?>

<section id="vocab">
    <form action="<?php echo $vocab->get_delete_link(); ?>" method="post">
        <ul class="tasks meta">
            <?php if ($vocab->is_active()): ?>
            <li>Active since <?php echo $vocab->get_init_date()->format('d F Y'); ?></li>
            <li>Level <?php echo $vocab->get_human_level(); ?></li>
            <?php else if ($vocab->is_burned()): ?>
            <li>Burned</li>
            <li><a href="<?php echo $vocab->get_resurrect_link(); ?>">Resurrect</a></li>
            <?php else: ?>
            <li>Inactive</li>
            <?php endif; ?>
            <li><button type="submit" class="delete">Delete</button></li>
        </ul>
    </form>

    <h2>
        <?php echo htmlentities($vocab->front); ?>
    </h2>

    <?php if ($nextvocab || $prevvocab): ?>
    <ol class="nav">
        <?php if ($prevvocab): ?>
        <li class="prev">
            <a href="<?php echo $prevvocab->get_permalink(); ?>">
                &larr; <?php echo htmlentities($prevvocab->front); ?>
            </a>
        </li>
        <?php endif; ?>
        <?php if ($nextvocab): ?>
        <li class="next">
            <a href="<?php echo $nextvocab->get_permalink(); ?>">
                <?php echo htmlentities($nextvocab->front); ?> &rarr;
            </a>
        </li>
        <?php endif; ?>
    </ol>
        <?php endif; ?>
</section>

<form action="<?php echo $vocab->get_edit_link(); ?>" method="post">
    <section class="back">
        <div class="inner">
            <?php echo $vocab->get_back(); ?>
        </div>
    </section>

    <textarea name="back" placeholder="Back"><?php echo htmlentities($vocab->back); ?></textarea>

    <section class="notes">
        <div class="inner">
            <?php echo $vocab->get_notes(); ?>
        </div>
    </section>

    <textarea name="notes" placeholder="Notes"><?php echo htmlentities($vocab->notes); ?></textarea>

    <p>
        <button type="submit">Update</button>
        <button type="reset">Cancel</button>
    </p>
</form>

<?php include 'footer.phtml'; ?>
